### PR TITLE
Rewrite... if interested

### PR DESCRIPTION
**Pull request by yormi**
Hi there !

I wanted to use your plugin but encountered bugs. Among other things, empty files were crashing the plugin... took me a while to see that it was the problem...

Anyway, rewrote most of it and it works for me now. Since I spent a lot of time on it, thought I'd share if anybody could see something useful in this.

Thank you for your work... saved my life with those annoying tables of content :)

### CODE REVIEW

**Comment by julianxhokaxhiu** [comment]
Sorry for the long time of no reply. I saw this only now.

First of all I would like to thank you very much for this. Looks like a solid rewrite of everything.

I always think that is safe enough to try, therefore I'll merge this, test it and then I'll publish if everything works good.

Before merging, may I ask if the code is up-to-date? If you need to push some more commits feel free to do so.

Best regards.

**Comment by yormi** [comment]
Hi Julian !

No worries, I understand that taking care of github project is just one bullet on an always growing TODO list :P

All I have is already pushed. You'll see if that brings you something or not :)

**Comment by julianxhokaxhiu** [comment]
I'm going to merge then :) Is it safe? I saw you merged new commits in your branch @yormi 

Were you able to test them?

**Comment by yormi** [comment]
To be honest, I haven't tested it but seeing the change, I'm quite confident. Haha, that's terrible to say as a programmer, right ?

It's basically adding a default value. I'm sorry to say that I'm not planning on testing it until I need it... The reality is that like probably everybody, I'm quite busy and I just wanted to merge the PR quickly to allow them to not wait for me. I trust that they'll fix it if they break it. If I wait to take the time, I fear to never do it =/

**Comment by julianxhokaxhiu** [comment]
Allright, I'll try to take some time and test it today. Meanwhile I'll merge it. If any PR is opened on your side, for the sake of keeping it synced, would be nice if they do it here. I'm open to add you as direct contributor on the repo, as well as discuss improvements :)

Thanks!

**Comment by jdeniau** [comment]
Hi @julianxhokaxhiu .

Thanks for the merge. If I write some other code, I will create the PR here, but @yormi code was more advanced.

Do you think you could push a new tag with this PR merged or you prefer test it before ?

**Comment by julianxhokaxhiu** [comment]
If you can ensure me it's working, I can push the tag. As I don't have a chance to use it actively, I will not be able to test it in the short term. Just ping me :)

**Comment by jdeniau** [comment]
@julianxhokaxhiu It does works for me yes, with 10 directory and 60 markdown files.

About my modification, you can see a rendering here:



The highlighted file contains no title, it does only contain a list of bullet points.

Thank you !

**Comment by julianxhokaxhiu** [comment]
Published as 1.0.0, also on NPM :)

**Comment by jdeniau** [comment]
Great thanks!

Le mar. 10 avr. 2018 à 22:53, Julian Xhokaxhiu <notifications@github.com> a
écrit :

**Pull request merged**
